[Template merge - langs/und] Make sure all generated files have a suffix that will make them be ignored. Added comments to clarify.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/sms@180795 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -2,10 +2,10 @@
 # @configure_input@
 
 # Automake interprets the exit status as follows:
-# - an exit status of 0 will denote a success (PASS)
-# - an exit status of 77 a skipped test (SKIP)
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
 # - an exit status of 99 a hard error
-# - any other exit status will denote a failure (FAIL)
+# - any other exit status will denote a failure.
 
 # To run this test script only, do:
 #
@@ -21,14 +21,21 @@
 
 
 ###### Variables: #######
+POS=verbs
 ### in ###
+#source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
 source_file=${srcdir}/../../../src/morphology/stems/V_sms2x.lexc
 generator_file=./../../../src/generator-gt-norm
+analyser_file=./../../../src/analyser-gt-norm
 
 ### out ###
-lemmas=./filtered-verbs
-generated_lemmas=./generated-verbs
-result_file=${srcdir}/missing_verb_lemmas.txt
+# Temporary files:
+lemmas=./filtered-${POS}.txt
+# Result files, will get filename suffix programmatically further down:
+generated_lemmas=./generated-${POS}
+result_file=missing_${POS}_lemmas
+gen_result_file=generated_missing_${POS}_lemmas
+ana_result_file=analysed_missing_${POS}_lemmas
 
 # SKIP if source file does not exist (works with both single and
 # multiple files):
@@ -129,7 +136,7 @@ done
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-	exit 1
+    exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
